baseurl = "https://example.org/"
languageCode = "en-us"
title = "John Doe's blog"
# Define how many pages appear per site
paginate = 10
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
themesDir = "../.."

[params]
    site_author = "John Doe"
    site_description = "The awesome blog of John Doe."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Customizable header title"
    copyright = "Powered by <a href=\"https://gohugo.io\" target=\"_blank\">Hugo</a>"
	  navbar_site_name = "Site Name"
    post_date = true
    post_tags = true
    
    # Remove or leave empty to remove comments. Add "comments = false" to post front matter to disable on individual posts.
    comments = "techstop/hugo-minimalist-theme"
    # Remove or leave empty defaulst to "github-light". Other themes: github-dark, github-dark-orange, icy-dark, dark-blue, photon-dark
    comments_theme = "github-light"
    
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "digitalcraftsman"
    gplus     = ""
